pool:
  name: Azure Pipelines
  vmImage: 'windows-2025'
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  solution: 'NLog.Web.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@2
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: Sonarcloud
    organization: nlog
    projectKey: nlog.web
    projectName: 'NLog Web'
    projectVersion: '$(Build.BuildId)'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(buildConfiguration)\**\NLog.*.Tests.dll
     !**\obj\**
    runOnlyImpactedTests: false
    runInParallel: false
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    failOnMinTestsNotRun: true
    rerunFailedTests: true
    rerunMaxAttempts: 5

- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Nupkg files to artifacts'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     artifacts\*.nupkg
     artifacts\*.snupkg
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: SonarCloudAnalyze@2
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@2
  displayName: 'Publish Quality Gate Result'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
